#################
# Bike detector configuration
#################
save_base: "clips_test"
model_yolo_path: "./models/yolov8n_ncnn_model"
detect_class: "cell phone" #"bicycle"         

min_box_w: 40
min_box_h: 40
save_crop_on_cross: true

line_y_ratio: 0.75

#################
# Camera options
#################

main_size: [4656, 3496]
lores_size: [864, 480]

camera_transform:
  vflip: true
  hflip: true

camera_controls:
  AfMode: 2
  AfTrigger: 0
  AfSpeed: 1
  ExposureTime: 0
  AnalogueGain: 0

inference:
  imgsz: 320
  conf: 0.35

#################
# plate detection options
#################
model_ocr_path: "./models/OCR/svm_ocr_arialv2.pkl"
aspect_target: 2.125         # 17/8
aspect_tol: 0.4              # ±40%
min_area_frac: 0.01
max_area_frac: 0.5

canny_values: [0, 255]
blur_kernel: [3, 3]
close_kernel: [3, 3]


###################
# Debugging options
draw_debug: true
window_name: "debug"